# Generated by Django 3.1.2 on 2020-12-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usual_deliver_time',
            field=models.IntegerField(default=5),
        ),
    ]
