# Generated by Django 3.1.2 on 2020-12-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_product_usual_deliver_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=100),
        ),
    ]
