# Generated by Django 3.1.2 on 2020-12-20 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('value', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=20)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumer', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
